<a href="https://colab.research.google.com/github/JohnPaulPrabhu/PyTorch_Training/blob/main/PyTorch_Essential_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch as t

a = t.tensor([[1,2,3],[4,5,6]])
b = t.tensor([[0,1,2],[3,4,5]])

print(a-b)
print(a+b)
print(a.size())
print(b.size())

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[ 1,  3,  5],
        [ 7,  9, 11]])
torch.Size([2, 3])
torch.Size([2, 3])


In [2]:
if t.cuda.is_available():
  device = "cuda"
else:
  device = 'cpu'

a = t.tensor([[1,2,3],[4,5,6]], device=device)
b = t.tensor([[0,1,2],[3,4,5]], device=device)

print(a*b)
# print(t.matmul(a,b)) matrix multiplication needs correct matrix size

tensor([[ 0,  2,  6],
        [12, 20, 30]], device='cuda:0')


In [3]:
emp = t.empty([2,3])
print(emp)

zeros = t.zeros(2,3)
print(zeros)

ones = t.ones([2,3], dtype=t.int16)
print(ones)

tensor([[-6.1745e-24,  4.3590e-41, -6.1745e-24],
        [ 4.3590e-41,  0.0000e+00,  0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [4]:
# Generate a tensor with a uniform distribution of random numbers
uniform_tensor = t.rand([2, 3])
print(uniform_tensor)

# Generate a tensor with a normal (Gaussian) distribution of random numbers
normal_tensor = t.randn([2, 3])
print(normal_tensor)

'''
- Generates a tensor with random integers
- The parameters 5 and 10 specify the range: 5 (inclusive) to 10 (exclusive)
- The shape of the output tensor is [2, 3]
'''
random_integer_tensor = t.randint(5, 10, [2, 3])
print(random_integer_tensor)

# Create a tensor of ones with the same shape as the randomly generated integer tensor
ones_like_tensor = t.ones_like(random_integer_tensor)
print(ones_like_tensor)


tensor([[0.7788, 0.9117, 0.7873],
        [0.1473, 0.0033, 0.0925]])
tensor([[ 2.1538, -0.7440, -0.0802],
        [-0.6317,  0.4038, -0.5248]])
tensor([[8, 9, 5],
        [6, 6, 5]])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [14]:
tensors = t.tensor([1,2,3,4]).reshape([2,2])
print(tensors)

tensor([[1, 2],
        [3, 4]])


In [13]:
'''
TO check the attribute of tensor, we can use the following functions on tensors
1. tensor.device - to check the device the tensor is reside in
2. tensor.dtype - Check the data type of the tensor
3. tensor.shape - Gives the dimention of the tensor
4. tensor.ndim - Provides the information about the dimension of the tensor
'''
tensor = t.tensor([[1,2,3], [3,4,5]])

print("Device that tensor is in: ", tensor.device)

print("Data type of the tensor: ", tensor.dtype)

print("Dimension of the tensor is: ", tensor.shape)

print("Dimensio of the tensor is: ", tensor.ndim)

Device that tensor is in:  cpu
Data type of the tensor:  torch.int64
Dimension of the tensor is:  torch.Size([2, 3])
Dimensio of the tensor is:  2
