<a href="https://colab.research.google.com/github/JohnPaulPrabhu/PyTorch_Training/blob/main/PyTorch_Essential_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch as t

a = t.tensor([[1,2,3],[4,5,6]])
b = t.tensor([[0,1,2],[3,4,5]])

print(a-b)
print(a+b)
print(a.size())
print(b.size())

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[ 1,  3,  5],
        [ 7,  9, 11]])
torch.Size([2, 3])
torch.Size([2, 3])


In [3]:
if t.cuda.is_available():
  device = "cuda"
else:
  device = 'cpu'

a = t.tensor([[1,2,3],[4,5,6]], device=device)
b = t.tensor([[0,1,2],[3,4,5]], device=device)

print(a*b)
# print(t.matmul(a,b)) matric multiplication needs proper matrix size

tensor([[ 0,  2,  6],
        [12, 20, 30]], device='cuda:0')


In [8]:
emp = t.empty([2,3])
print(emp)

zeros = t.zeros(2,3)
print(zeros)

ones = t.ones([2,3], dtype=t.int16)
print(ones)

tensor([[1.3304e-08, 3.1381e-41, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [14]:
# UNiform distribution
print(t.rand([2,3]))

# Normal Distribution
print(t.randn([2,3]))

# Uniform distribution
print(t.randint(5,10,[2,3]))

# Ones like
print(t.ones_like(t.randint(5,10,[2,3])))

tensor([[0.6535, 0.6850, 0.9247],
        [0.1632, 0.7463, 0.1063]])
tensor([[ 0.3027, -0.5915, -0.5369],
        [-0.0302, -0.3780,  1.7283]])
tensor([[5, 7, 9],
        [6, 8, 9]])
tensor([[1, 1, 1],
        [1, 1, 1]])
