<a href="https://colab.research.google.com/github/JohnPaulPrabhu/PyTorch_Training/blob/main/PyTorch_Essential_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Basics

In [1]:
import torch as t

a = t.tensor([[1,2,3],[4,5,6]])
b = t.tensor([[0,1,2],[3,4,5]])

print(a-b)
print(a+b)
print(a.size())
print(b.size())

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[ 1,  3,  5],
        [ 7,  9, 11]])
torch.Size([2, 3])
torch.Size([2, 3])


In [2]:
if t.cuda.is_available():
  device = "cuda"
else:
  device = 'cpu'

a = t.tensor([[1,2,3],[4,5,6]], device=device)
b = t.tensor([[0,1,2],[3,4,5]], device=device)

print(a*b)
# print(t.matmul(a,b)) matrix multiplication needs correct matrix size

tensor([[ 0,  2,  6],
        [12, 20, 30]], device='cuda:0')


In [3]:
emp = t.empty([2,3])
print(emp)

zeros = t.zeros(2,3)
print(zeros)

ones = t.ones([2,3], dtype=t.int16)
print(ones)

tensor([[2.4079e-15, 4.3379e-41, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


### Generating random values

In [4]:
# Generate a tensor with a uniform distribution of random numbers
uniform_tensor = t.rand([2, 3])
print(uniform_tensor)

# Generate a tensor with a normal (Gaussian) distribution of random numbers
normal_tensor = t.randn([2, 3])
print(normal_tensor)

'''
- Generates a tensor with random integers
- The parameters 5 and 10 specify the range: 5 (inclusive) to 10 (exclusive)
- The shape of the output tensor is [2, 3]
'''
random_integer_tensor = t.randint(5, 10, [2, 3])
print(random_integer_tensor)

# Create a tensor of ones with the same shape as the randomly generated integer tensor
ones_like_tensor = t.ones_like(random_integer_tensor)
print(ones_like_tensor)


tensor([[0.4434, 0.6142, 0.1399],
        [0.8501, 0.1305, 0.6992]])
tensor([[-1.5208,  1.3141, -0.1109],
        [ 0.3134, -0.8329, -0.2648]])
tensor([[9, 9, 5],
        [8, 8, 9]])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [5]:
tensors = t.tensor([1,2,3,4]).reshape([2,2])
print(tensors)

tensor([[1, 2],
        [3, 4]])


### Attributes of Tensors

In [6]:
'''
TO check the attribute of tensor, we can use the following functions on tensors
1. tensor.device - to check the device the tensor is reside in
2. tensor.dtype - Check the data type of the tensor
3. tensor.shape - Gives the dimention of the tensor
4. tensor.ndim - Provides the information about the dimension of the tensor
'''
tensor = t.tensor([[1,2,3], [3,4,5]])

print("Device that tensor is in: ", tensor.device)

print("Data type of the tensor: ", tensor.dtype)

print("Dimension of the tensor is: ", tensor.shape)

print("Dimensio of the tensor is: ", tensor.ndim)

Device that tensor is in:  cpu
Data type of the tensor:  torch.int64
Dimension of the tensor is:  torch.Size([2, 3])
Dimensio of the tensor is:  2


### Data types of Tensors

In [7]:
"""
We have different types of the data types available in PyTorch
1. int8
2. int16
3. int32
4. int64
5. uint8
6. uint16
7. uint32
8. uint64
9. float8
10. float16
11. float32
12. float64
and so on
There are multiple data types availble in PyTorch
"""
one_dim_tensor = t.tensor([1,2,3,4,5,6,255], dtype=t.uint8)
print(one_dim_tensor)

# Incase we need to cast an another type to existing tensor, then we can do the following
one_dim_tensor = one_dim_tensor.float()
print(one_dim_tensor.dtype)

# We can also use the .to function to change the data type or device
one_dim_tensor = one_dim_tensor.to(dtype=t.float16)
print(one_dim_tensor)

tensor([  1,   2,   3,   4,   5,   6, 255], dtype=torch.uint8)
torch.float32
tensor([  1.,   2.,   3.,   4.,   5.,   6., 255.], dtype=torch.float16)


In [8]:
'''
- When we run the below code, each time we will get different values
- To avoid it, we can use something called seed
'''
t.manual_seed(11)

#Create random samples from normal distribution
random_sample = t.randn(3, 3)
print(random_sample)

# Create random sample from Uniform distribution
uniform_sample = t.rand(3, 3)
print(uniform_sample)

# Create random integers
rand_int = t.randint(1,10,(3,3))
print(rand_int)

tensor([[ 0.7376,  1.9459, -0.6995],
        [-1.3023, -0.5133, -0.2696],
        [ 0.2462,  0.4839,  0.4504]])
tensor([[0.8709, 0.7231, 0.8364],
        [0.5820, 0.8395, 0.0595],
        [0.4315, 0.4425, 0.2622]])
tensor([[9, 2, 5],
        [1, 5, 5],
        [8, 4, 5]])


In [9]:
'''
We can create tensor based on other tensor
There are three functions we can use to achieve this result
1. rand_like - This will provide the values from uniform distribution that has
               same size as the mentioned tensor
2. ones_like - Create tensors of 1
3. full_like - Create tensors of mentioned number
'''
import torch as t
ten = t.tensor([[1,2,3,4],[5,6,7,8]])

rand_likes = t.rand_like(uniform_sample)
print(rand_likes)

one = t.ones_like(ten)
print(one)

full = t.full_like(ten, 333)
print(full)

tensor([[0.4256, 0.4382, 0.2988],
        [0.8474, 0.4785, 0.1935],
        [0.2239, 0.5639, 0.6125]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[333, 333, 333, 333],
        [333, 333, 333, 333]])


### Tensor Operations

In [10]:
# Accessing data in 1D tensors is same as accessing data in List
data = t.tensor([1,2,3,4,5])
print(data[4])

# If you want just the value, not the type then We can use .item() function
print(data[4].item())

# Slicing is same as List slicing
# [start:end:step]
print(data[1:4])
print(data[1:4:2])

# access data in 2D data
data_2d = t.tensor([[1,2,3,4,5],[6,7,8,9,10],[2,4,6,8,10]])
print(data_2d[0][3])

# Slicing in 2D data
print(data_2d[2, 0:3])

# We can also use condition on slicing
print(data_2d[data_2d < 10])

# Combine 2 tensors
print(t.stack((data_2d, data_2d)))

# Split tensors
print(t.unbind(data_2d))

# While spliting we can also use the dim=1 to split it by column
print(t.unbind(data_2d, dim=1))

tensor(5)
5
tensor([2, 3, 4])
tensor([2, 4])
tensor(4)
tensor([2, 4, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 4, 6, 8])
tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [ 2,  4,  6,  8, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [ 2,  4,  6,  8, 10]]])
(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]), tensor([ 2,  4,  6,  8, 10]))
(tensor([1, 6, 2]), tensor([2, 7, 4]), tensor([3, 8, 6]), tensor([4, 9, 8]), tensor([ 5, 10, 10]))
